"""Generate src/tables.rs from the reference interpreter's Unicode database.

The Rust port must see exactly the character properties the measured Python
reference (py/frozen/umath_v3.py under CPython 3.11, Unicode 14.0) sees:
str.isalpha/isdecimal/isdigit/isalnum/isspace/isupper/islower, category Mn
and Lt, the reference's own mathalpha_latex() and subsup_of() tables, the NFD
shape _precomposed_math() looks for, and the house-label lexicon. Rust's own
char methods use a newer Unicode and slightly different definitions
(e.g. char::is_alphabetic != str.isalpha), so nothing is taken from them.

Run from the spike root:  python3 rs/umath/tools/gen_tables.py
"""
import importlib.util
import json
import sys
import unicodedata

spec = importlib.util.spec_from_file_location('umath_v3', 'py/frozen/umath_v3.py')
U = importlib.util.module_from_spec(spec)
sys.modules['umath_v3'] = U
spec.loader.exec_module(U)

ALPHA, DECIMAL, DIGIT, ALNUM, SPACE, UPPER, LOWER, TITLE, MN = (1 << k for k in range(9))


def flags(c):
    f = 0
    if c.isalpha(): f |= ALPHA
    if c.isdecimal(): f |= DECIMAL
    if c.isdigit(): f |= DIGIT
    if c.isalnum(): f |= ALNUM
    if c.isspace(): f |= SPACE
    if c.isupper(): f |= UPPER          # single char: the Uppercase property
    if c.islower(): f |= LOWER
    cat = unicodedata.category(c)
    if cat == 'Lt': f |= TITLE          # CPython's TITLE_MASK is category Lt
    if cat == 'Mn': f |= MN
    return f


ranges = []
cur = None
for o in range(0x110000):
    if 0xD800 <= o <= 0xDFFF:
        f = 0                            # surrogates cannot occur in a Rust char
    else:
        f = flags(chr(o))
    if cur and cur[2] == f and cur[1] == o - 1:
        cur[1] = o
    else:
        if cur and cur[2]:
            ranges.append(tuple(cur))
        cur = [o, o, f]
if cur and cur[2]:
    ranges.append(tuple(cur))

subsup, malpha, precomp, raises = [], [], [], []
for o in range(0x110000):
    if 0xD800 <= o <= 0xDFFF:
        continue
    c = chr(o)
    ss = U.subsup_of(c)
    if ss:
        subsup.append((o, ss[0] == 'sup', ss[1]))
    try:
        m = U.mathalpha_latex(c)
    except Exception:
        # the reference raises here (U+1D7CA/B bold digamma: Unicode names the
        # Greek letter 'GREEK LETTER DIGAMMA', no CAPITAL), so convert() raises
        raises.append(o)
        continue
    if m is not None:
        malpha.append((o, m))
    d = unicodedata.normalize('NFD', c)
    if len(d) == 2 and d[0].isascii() and d[1] in ('̇', '̈', '̂', '̄', '̃'):
        precomp.append((o, d[0], d[1]))


def rs_char(c):
    return "'\\u{%x}'" % ord(c)


def rs_str(s):
    return '"' + ''.join(ch if ch.isascii() and ch.isprintable() and ch not in '"\\' else
                         ('\\\\' if ch == '\\' else '\\"' if ch == '"' else '\\u{%x}' % ord(ch)) for ch in s) + '"'


out = []
out.append('// @generated by tools/gen_tables.py from CPython %s, Unicode %s.\n'
           '// Do not edit; regenerate. See PORT.md "Unicode tables".\n' % (sys.version.split()[0], unicodedata.unidata_version))
out.append('pub const ALPHA: u16 = 1;\npub const DECIMAL: u16 = 2;\npub const DIGIT: u16 = 4;\n'
           'pub const ALNUM: u16 = 8;\npub const SPACE: u16 = 16;\npub const UPPER: u16 = 32;\n'
           'pub const LOWER: u16 = 64;\npub const TITLE: u16 = 128;\npub const MN: u16 = 256;\n')
out.append('/// (first, last, flags), sorted, non-overlapping; absent = 0.\n'
           'pub static FLAG_RANGES: &[(u32, u32, u16)] = &[\n')
for a, b, f in ranges:
    out.append(f'    (0x{a:x}, 0x{b:x}, {f}),\n')
out.append('];\n')
out.append('/// subsup_of(): (char, is_super, base), sorted by char.\n'
           'pub static SUBSUP: &[(char, bool, char)] = &[\n')
for o, sup, base in subsup:
    out.append(f'    ({rs_char(chr(o))}, {"true" if sup else "false"}, {rs_char(base)}),\n')
out.append('];\n')
out.append('/// mathalpha_latex(), sorted by char.\n'
           'pub static MATHALPHA: &[(char, &str)] = &[\n')
for o, m in malpha:
    out.append(f'    ({rs_char(chr(o))}, {rs_str(m)}),\n')
out.append('];\n')
out.append('/// NFD(c) == base + mark, base ASCII, mark one of the five math accents; sorted.\n'
           'pub static PRECOMPOSED: &[(char, char, char)] = &[\n')
for o, b, m in precomp:
    out.append(f'    ({rs_char(chr(o))}, {rs_char(b)}, {rs_char(m)}),\n')
out.append('];\n')
out.append('/// mathalpha_latex() raises on these (the reference convert() then raises).\n'
           'pub static MATHALPHA_RAISES: &[char] = &[' + ', '.join(rs_char(chr(o)) for o in raises) + '];\n')
# v6: KNOWN_COMMANDS for commands_known(), from v6's own _known_commands();
# and v6's mathalpha table must equal v5's minus the raising char(s).
spec6 = importlib.util.spec_from_file_location('umath_v6', 'py/frozen/umath_v6.py')
U6 = importlib.util.module_from_spec(spec6)
sys.modules['umath_v6'] = U6
spec6.loader.exec_module(U6)
for o in range(0x110000):
    if 0xD800 <= o <= 0xDFFF:
        continue
    want = None if o in raises else dict(malpha).get(o)
    assert U6.mathalpha_latex(chr(o)) == want, hex(o)
    assert U6.subsup_of(chr(o)) == U.subsup_of(chr(o)), hex(o)
known = sorted(U6._known_commands())
out.append('/// umath_v6 KNOWN_COMMANDS (`_known_commands()`), sorted.\n'
           'pub static KNOWN_COMMANDS: &[&str] = &[\n' + ''.join(f'    {rs_str(x)},\n' for x in known) + '];\n')
labels = sorted(json.load(open('data/house-labels-asf-canon.json')))
assert set(labels) == U.HOUSE_LABELS, (labels, U.HOUSE_LABELS)
out.append('/// data/house-labels-asf-canon.json (keys), as loaded by the reference.\n'
           'pub static HOUSE_LABELS: &[&str] = &[' + ', '.join(rs_str(x) for x in labels) + '];\n')

open('rs/umath/src/tables.rs', 'w').write(''.join(out))
print(f'{len(ranges)} flag ranges, {len(subsup)} sub/sup, {len(malpha)} mathalpha, {len(precomp)} precomposed, {len(raises)} raising, '
      f'{len(labels)} house labels, {len(known)} known commands')
